title: "Railgun"
description: "Railgun Doc"
themeConfig:
  sidebarDepth: 3
  nav:
    - text: "Home"
      link: "/"
    - text: "Doc"
      link: "/doc/"
    - text: "API"
      link: "/api/"
    - text: "Github"
      link: "https://github.com/railgun-project/railgun"
  sidebar:
    /doc/:
      - "":
        title: Document
        collapsable: false
        children:
          - "test"
